name: cifarx_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #for internet connection:
  connectivity_plus:
  #for logging the error:
  logger:
  #for loader :
  flutter_spinkit:
  #for storage :
  get_storage:
  #http package
  http: ^1.4.0
  #for caching image
  cached_network_image: ^3.4.1
  #for date time:
  intl: ^0.20.2
  #for route management
  go_router: ^16.3.0
  #for state management
  flutter_riverpod: ^3.0.3
  riverpod:


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  riverpod_lint: ^3.0.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
#    - assets/fonts/satoshi




  fonts:
    - family: satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf




